### PR TITLE
client: log the response body on errors fetching a token

### PR DESCRIPTION
**Pull request by grahamc**
I was getting mysterious 403 errors creating new tokens.

After this patch, I was able to see an underlying error:

    Request forbidden by administrative rules. Please make sure your
    request has a User-Agent header
    (http://developer.github.com/v3/#user-agent-required). Check
    https://developer.github.com for other possible causes.

which revealed I needed to add:

    buildFlagsArray = [ "-ldflags=-s -w -X github.com/martinbaillie/vault-plugin-secrets-github/github.projectName=martinbaillie/vault-plugin-secrets-github" ];

to my Nix expression.

### CODE REVIEW

**Review by martinbaillie — APPROVED** [review]

**Comment by grahamc** [comment]
Thank you a lot! I'm really appreciating this provider. I made a party-trick-quality git-remote transport with it as a demo :)

```
$ git push github://grahamc/xxx.git
---> Provisioning ephemeral token to push to grahamc/xxx.git
[...]
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github://grahamc/xxx.git
   b21f690..7650106  lol -> lol
---> Token revoked.
```

**Comment by martinbaillie** [comment]
🤯 that's awesome. TIL about https://git-scm.com/docs/gitremote-helpers! 

Food for thought on how I might use one myself actually...

**Comment by grahamc** [comment]
```sh
#!/bin/sh

target=$1
shift
repo=$(echo "$target" | sed -e 's#^github://##')

echo "---> Provisioning ephemeral token to push to $repo" >&2
token=$(vault write -field token /github/token permissions=contents=write)
git remote-https "https://x-access-token:$token@github.com/$repo"
exitcode=$?
echo "---> Token revoked." >&2
exit $exitcode
```

Like I said, party-trick-quality, and the "revoked" bit is actually lying, but good for a demo! :wink:

**Comment by martinbaillie** [comment]
Pays to understand what lies beneath the git porcelains sometimes ey!

I reckon a 
`curl  -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $token" -X DELETE https://api.github.com/installation/token` would keep you honest

**Pull request merged**
