### PR TITLE
Implement permission set

### LINKED ISSUE #14: Support for roles?
I think it'd be neat to be able to define a role which has predefined repositories and access levels defined in the role, as opposed to requiring the requester to specify them. Are you interested in that?

### PR DESCRIPTION
**Pull request by lsjostro**
This implements permissions sets (just like roleset for the [gcp secret engine](https://www.vaultproject.io/docs/secrets/gcp)). This makes it easy to write vault policies.
You create a set of permissions on a named endpoint i.e: `github/permissionset/readonly` and to request a token with that permission set you access `github/token/readonly`. It does not break existing API though.

I think this should fix #14

### CODE REVIEW

**Comment by lsjostro** [comment]
Temporarily release (until we can have this PR merged). We are using this in prod already. 
https://github.com/shelmangroup/vault-plugin-secrets-github/releases/download/v1.1.0/vault-plugin-secrets-github-linux-amd64
https://github.com/shelmangroup/vault-plugin-secrets-github/releases/download/v1.1.0/vault-plugin-secrets-github-linux-amd64.sha254

**Comment by martinbaillie** [comment]
Thanks @lsjostro I've seen this PR and it sounds like a great use of lateral knowledge of how other plugins do this sort of thing. I'm hoping to look properly and get it merged and released at the weekend!

**Review by martinbaillie — APPROVED** [review]
Looks great. Thanks!

**Comment by martinbaillie** [comment]
This is now available in https://github.com/martinbaillie/vault-plugin-secrets-github/releases/tag/v1.1.0

**Pull request merged**
